### ISSUE TITLE
Not generating absolute paths from relative paths

### ISSUE THREAD

**Issue by cob-web-corner** [containers/podlet#102]
```podlet compose --kube docker-compose.yaml```

The compose:
```yaml
  the_service:
    volumes:
      - /run/user/1001/podman/podman.sock:/var/run/docker.sock
      - ./data:/data
      - ./config.yaml:/config.yaml
    container_name: container_name
    image: container/image:latest
```

Resulting yaml
```yaml
  - hostPath:
      path: ./data
    name: container_data
  - hostPath:
      path: ./config.yaml
    name: **container_config.yaml**
```

Obviously not a whole real-example but just to demonstrate. The only way the resulting kube file can be used in a corresponding `.kube` service is by using absolute paths. During the podlet run it should convert these paths

### Version
```
$ podlet --version
podlet 0.3.0
```
