### ISSUE TITLE
must warn about unhandled `healthcheck` command and other options with variables

### ISSUE THREAD

**Issue by akostadinov** [containers/podlet#103]
Docker compose seems to replace variables in different commands. This doesn't seem to be the case with systemd.

Take this compose file for example: [v1.114.0](https://github.com/immich-app/immich/releases/tag/v1.114.0)

Specifically this part:
```
     healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
```

The variables `DB_*` are not replaced (which is good). But they don't work. To make this work I had to remove the quotes and make `$` double `&&`. While keepin gthe other places as they are.

I understand that fixing a random bash command might be impossible. But would be helpful if there is a warning line stating that docker compose would replace these commands before runningthe command in bash while systemd service will not. Maybe some link to an explanation how to fix such commands in general.

Like in this case it is enough to remove the quotes and make double dollar `$$`. But there might be other considerations when the strings may need quoting. 

I think the issue is only with variables that docker-compose would replace. Where shell is supposed to be expanding, original version appears to be fine.
