### ISSUE TITLE
unknown volume option: rslave

### ISSUE THREAD

**Issue by kavishgr** [containers/podlet#104]
Podlet version: **0.3.0**

Trying to convert the following `compose.yaml` file:

```yaml
services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
```

Getting the following errors:

```console
➜  podlet-aarch64-apple-darwin export RUST_BACKTRACE=full; ./podlet compose compose.yaml
Error:
   0: error converting compose file
   1: error reading compose file
   2: File `compose.yaml` is not a valid compose file
   3: services.node_exporter.volumes[0]: unknown volume option `rslave` at line 11 column 9

Location:
   src/cli/compose.rs:203

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                ⋮ 4 frames hidden ⋮
   5: podlet::cli::compose::Compose::try_into_files::h730d49aecca088e4
      at <unknown source file>:<unknown line>
   6: podlet::cli::Cli::try_into_files::ha49fd64a54badb30
      at <unknown source file>:<unknown line>
   7: podlet::cli::Cli::print_or_write_files::hc05bd620f32ffc35
      at <unknown source file>:<unknown line>
   8: podlet::main::h11cc216fce298a6f
      at <unknown source file>:<unknown line>
   9: std::sys_common::backtrace::__rust_begin_short_backtrace::h54bce024b30e1ddd
      at <unknown source file>:<unknown line>
  10: std::rt::lang_start::{{closure}}::h97f4928545f52a78
      at <unknown source file>:<unknown line>
  11: std::rt::lang_start_internal::h39923ab4c3913741
      at <unknown source file>:<unknown line>
  12: _main<unknown>
      at <unknown source file>:<unknown line>
```
