### ISSUE TITLE
Could not convert compose file with ports

### ISSUE THREAD

**Issue by Chaz6** [containers/podlet#109]
Error output:-

```
   4: could not convert port to short syntax, port = Port {                                                                              
          name: None,
          target: 80,
          published: Some(
              Range {
                  start: 80,
                  end: None,
              },
          ),
          host_ip: None,
          protocol: Some(
              Tcp,
          ),
          app_protocol: None,
          mode: Some(
              Host,
          ),
          extensions: {},
      }
```

From `docker-compose.yml`:-

```
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: udp
        mode: host
```
