### ISSUE TITLE
Podlet Gives an Error With --security-opt label=type:spc_t

### ISSUE THREAD

**Issue by JMOdero** [containers/podlet#120]
Podlet refuses to convert files when --security-opt label=type:spc_t is used.
```
    plex:
        image: lscr.io/linuxserver/plex:latest
        container_name: plex
        security_opt:
            - label=type:plex.process
        network_mode: container:vpn
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
        volumes:
            - /mnt/blahblah/blahblah/plex/config:/config
            - /mnt/blahblah/blahblah/media:/media
        restart: unless-stopped
```
I ended up getting this...
```
$ sudo /root/.cargo/bin/podlet compose --pod media.yaml
Error: 
   0: error converting compose file
   1: error converting compose file into Quadlet files
   2: error converting service `plex` into a Quadlet container
   3: invalid security option
   4: `type=plex.process` is not a valid label option
```
I _think_ it should have spat out something like this...
`SecurityLabelType=plex.process`

![Image](https://github.com/user-attachments/assets/94e09323-d96f-4519-b363-509781a966da)

I have all types of custom security labels such as vpn.process, homepage.process, etc.  I believe custom security labels can be called anything, for example afdionsaod.process if you want.

For analyzing compose files there should be something like a wild card... - label=type:*

You would still be able to check for...
```
- label=disable
- label=nested
```
and however you handle things like this...
```
- label=level:s0:c1,c2
- label=filetype:usr_t
```
