### ISSUE TITLE
Compose with build section: `image` or `build` is required.

### ISSUE THREAD

**Issue by Timon-Schneider** [containers/podlet#126]
I have compiled the latest code as I have seen that it should now be possible to use the build section in compose files, but unfortunately it does not work as expected. I think it tries to find the image section even though there is a build section.

```
Error:
   0: error converting compose file
   1: error converting compose file into Quadlet files
   2: error converting service `jupyter` into a Quadlet container
   3: `image` or `build` is required
```

```
version: '3'
services:
  jupyter:
    build: 
      context: .
      dockerfile: ./docker/jupyter/Dockerfile
    volumes:
      - ./work:/home/jovyan/work
    ports:
      - 8888:8888
    command: "start-notebook.sh --NotebookApp.token="
```

I tried: 

```
version: '3'
services:
  jupyter:
    build: ./docker/jupyter
    volumes:
      - ./work:/home/jovyan/work
    ports:
      - 8888:8888
    command: "start-notebook.sh --NotebookApp.token="
```

but still no success.

**Comment by k9withabone** [comment]
Huh, you should be getting an error like "an image tag is required" as the `ImageTag=` option is required by Quadlet. I'll look into it.

**Comment by Timon-Schneider** [comment]
Thanks so much for the quick response! The pull request seems to have solved the problem. The only thing that confused me a bit was the error message, "an image tag is required". I didn't know exactly how to map this in the compose file. After a few attempts, I created the following compose file, which seems to be working. 

```
version: '3'
services:
  jupyter:
    build:
      context: .
      dockerfile: ./docker/jupyter/Dockerfile
      tags:
        - "myapp:1.0"
    volumes:
      - ./work:/home/jovyan/work
    ports:
      - 8888:8888
    command: "start-notebook.sh --NotebookApp.token="
```

Here's the result:

```
# jupyter.container
[Container]
Exec=start-notebook.sh '--NotebookApp.token='
Image=myapp.build
PublishPort=8888:8888
Volume=./work:/home/jovyan/work

---

# myapp.build
[Build]
File=./docker/jupyter/Dockerfile
ImageTag=myapp:1.0
SetWorkingDirectory=.
```
