### ISSUE TITLE
Support for external managed networks

### ISSUE THREAD

**Issue by ZzenlD** [containers/podlet#95]
I have the following docker-compose file:

```yaml
version: "3.9"
services:
  traefik:
    image: docker.io/traefik:v3.0.3
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./traefik/etc:/etc/traefik:z
      - ./traefik/var/acme.json:/acme.json:z
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external:
      name: proxy
```

The command `podman run --rm -v ./docker-compose.yml:/docker-compose.yml:Z ghcr.io/containers/podlet compose /docker-compose.yml` fails with the following error message:

```
Error: 
   0: error converting compose file
   1: error reading compose file
   2: File `/docker-compose.yml` is not a valid compose file
   3: networks: invalid type: map, expected a boolean at line 22 column 3

Location:
   src/cli/compose.rs:203

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

If you remove `external: name: proxy` from the networks section, it works.

Would like it if external networks are supported, as this option is especially helpful with reverse proxies and multiple standalone docker-compose files for more clarity.
